server:
  port: 8082

spring:
  application:
    name: process-service
  datasource:
    username: root
    password: grh233..
    url: jdbc:mysql://localhost:3306/process?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: always
      username: root
      password: grh233..
      schema-locations:
        - classpath:database/process_initialize.sql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
