server:
  port: 8082

spring:
  application:
    name: process-service
  datasource:
    username: root
    password: grhlyyzcx
    url: jdbc:mysql://150.158.95.209:30632/process?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: always
      username: root
      password: grhlyyzcx
      schema-locations:
        - classpath:database/process_initialize.sql
      data-locations:
        - classpath:database/process_data.sql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://150.158.95.209:38160/eureka/