server:
  port: 7777

spring:
  application:
    name: resume-service
  datasource:
    username: root
    password: grh233..
    url: jdbc:mysql://localhost:3306/resume?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/
