server:
  port: 8081

spring:
  application:
    name: login-service
  datasource:
    username: root
    password: grhlyyzcx
    url: jdbc:mysql://localhost:3306/login?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  sql:
    init:
      mode: always
      username: root
      password: grhlyyzcx
      schema-locations:
        - classpath:database/login_initialize.sql
      data-locations:
        - classpath:database/login_data.sql
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/