server:
  port: 8081

spring:
  application:
    name: login-service
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/login?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka/